// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ledger_info.proto

package types;

public final class LedgerInfoOuterClass {
  private LedgerInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LedgerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:types.LedgerInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Current latest version of the system
     * </pre>
     *
     * <code>uint64 version = 1;</code>
     */
    long getVersion();

    /**
     * <pre>
     * Root hash of transaction accumulator at this version
     * </pre>
     *
     * <code>bytes transaction_accumulator_hash = 2;</code>
     */
    com.google.protobuf.ByteString getTransactionAccumulatorHash();

    /**
     * <pre>
     * Hash of consensus-specific data that is opaque to all parts of the system
     * other than consensus.  This is needed to verify signatures because
     * consensus signing includes this hash
     * </pre>
     *
     * <code>bytes consensus_data_hash = 3;</code>
     */
    com.google.protobuf.ByteString getConsensusDataHash();

    /**
     * <pre>
     * The block id of the last committed block corresponding to this ledger info.
     * This field is not particularly interesting to the clients, but can be used
     * by the validators for synchronization.
     * </pre>
     *
     * <code>bytes consensus_block_id = 4;</code>
     */
    com.google.protobuf.ByteString getConsensusBlockId();

    /**
     * <pre>
     * Epoch number corresponds to the set of validators that are active for this
     * ledger info. The main motivation for keeping the epoch number in the
     * LedgerInfo is to ensure that the client has enough information to verify
     * that the signatures for this info are coming from the validators that
     * indeed form a quorum. Without epoch number a potential attack could reuse
     * the signatures from the validators in one epoch in order to sign the wrong
     * info belonging to another epoch, in which these validators do not form a
     * quorum. The very first epoch number is 0.
     * </pre>
     *
     * <code>uint64 epoch_num = 5;</code>
     */
    long getEpochNum();

    /**
     * <pre>
     * Timestamp that represents the microseconds since the epoch (unix time) that is
     * generated by the proposer of the block.  This is strictly increasing with every block.
     * If a client reads a timestamp &gt; the one they specified for transaction expiration time,
     * they can be certain that their transaction will never be included in a block in the future
     * (assuming that their transaction has not yet been included)
     * </pre>
     *
     * <code>uint64 timestamp_usecs = 6;</code>
     */
    long getTimestampUsecs();
  }
  /**
   * <pre>
   *&#47; Even though we don't always need all hashes, we pass them in and return them
   * / always so that we keep them in sync on the client and don't make the client
   * / worry about which one(s) to pass in which cases
   * /
   * / This structure serves a dual purpose.
   * /
   * / First, if this structure is signed by 2f+1 validators it signifies the state
   * / of the ledger at version `version` -- it contains the transaction
   * / accumulator at that version which commits to all historical transactions.
   * / This structure may be expanded to include other information that is derived
   * / from that accumulator (e.g. the current time according to the time contract)
   * / to reduce the number of proofs a client must get.
   * /
   * / Second, the structure contains a `consensus_data_hash` value. This is the
   * / hash of an internal data structure that represents a block that is voted on
   * / by consensus.
   * /
   * / Combining these two concepts when the consensus algorithm votes on a block B
   * / it votes for a LedgerInfo with the `version` being the latest version that
   * / will be committed if B gets 2f+1 votes. It sets `consensus_data_hash` to
   * / represent B so that if those 2f+1 votes are gathered, the block is valid to
   * / commit
   * </pre>
   *
   * Protobuf type {@code types.LedgerInfo}
   */
  public  static final class LedgerInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:types.LedgerInfo)
      LedgerInfoOrBuilder {
    // Use LedgerInfo.newBuilder() to construct.
    private LedgerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LedgerInfo() {
      version_ = 0L;
      transactionAccumulatorHash_ = com.google.protobuf.ByteString.EMPTY;
      consensusDataHash_ = com.google.protobuf.ByteString.EMPTY;
      consensusBlockId_ = com.google.protobuf.ByteString.EMPTY;
      epochNum_ = 0L;
      timestampUsecs_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LedgerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              version_ = input.readUInt64();
              break;
            }
            case 18: {

              transactionAccumulatorHash_ = input.readBytes();
              break;
            }
            case 26: {

              consensusDataHash_ = input.readBytes();
              break;
            }
            case 34: {

              consensusBlockId_ = input.readBytes();
              break;
            }
            case 40: {

              epochNum_ = input.readUInt64();
              break;
            }
            case 48: {

              timestampUsecs_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return types.LedgerInfoOuterClass.internal_static_types_LedgerInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return types.LedgerInfoOuterClass.internal_static_types_LedgerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              types.LedgerInfoOuterClass.LedgerInfo.class, types.LedgerInfoOuterClass.LedgerInfo.Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private long version_;
    /**
     * <pre>
     * Current latest version of the system
     * </pre>
     *
     * <code>uint64 version = 1;</code>
     */
    public long getVersion() {
      return version_;
    }

    public static final int TRANSACTION_ACCUMULATOR_HASH_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString transactionAccumulatorHash_;
    /**
     * <pre>
     * Root hash of transaction accumulator at this version
     * </pre>
     *
     * <code>bytes transaction_accumulator_hash = 2;</code>
     */
    public com.google.protobuf.ByteString getTransactionAccumulatorHash() {
      return transactionAccumulatorHash_;
    }

    public static final int CONSENSUS_DATA_HASH_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString consensusDataHash_;
    /**
     * <pre>
     * Hash of consensus-specific data that is opaque to all parts of the system
     * other than consensus.  This is needed to verify signatures because
     * consensus signing includes this hash
     * </pre>
     *
     * <code>bytes consensus_data_hash = 3;</code>
     */
    public com.google.protobuf.ByteString getConsensusDataHash() {
      return consensusDataHash_;
    }

    public static final int CONSENSUS_BLOCK_ID_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString consensusBlockId_;
    /**
     * <pre>
     * The block id of the last committed block corresponding to this ledger info.
     * This field is not particularly interesting to the clients, but can be used
     * by the validators for synchronization.
     * </pre>
     *
     * <code>bytes consensus_block_id = 4;</code>
     */
    public com.google.protobuf.ByteString getConsensusBlockId() {
      return consensusBlockId_;
    }

    public static final int EPOCH_NUM_FIELD_NUMBER = 5;
    private long epochNum_;
    /**
     * <pre>
     * Epoch number corresponds to the set of validators that are active for this
     * ledger info. The main motivation for keeping the epoch number in the
     * LedgerInfo is to ensure that the client has enough information to verify
     * that the signatures for this info are coming from the validators that
     * indeed form a quorum. Without epoch number a potential attack could reuse
     * the signatures from the validators in one epoch in order to sign the wrong
     * info belonging to another epoch, in which these validators do not form a
     * quorum. The very first epoch number is 0.
     * </pre>
     *
     * <code>uint64 epoch_num = 5;</code>
     */
    public long getEpochNum() {
      return epochNum_;
    }

    public static final int TIMESTAMP_USECS_FIELD_NUMBER = 6;
    private long timestampUsecs_;
    /**
     * <pre>
     * Timestamp that represents the microseconds since the epoch (unix time) that is
     * generated by the proposer of the block.  This is strictly increasing with every block.
     * If a client reads a timestamp &gt; the one they specified for transaction expiration time,
     * they can be certain that their transaction will never be included in a block in the future
     * (assuming that their transaction has not yet been included)
     * </pre>
     *
     * <code>uint64 timestamp_usecs = 6;</code>
     */
    public long getTimestampUsecs() {
      return timestampUsecs_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (version_ != 0L) {
        output.writeUInt64(1, version_);
      }
      if (!transactionAccumulatorHash_.isEmpty()) {
        output.writeBytes(2, transactionAccumulatorHash_);
      }
      if (!consensusDataHash_.isEmpty()) {
        output.writeBytes(3, consensusDataHash_);
      }
      if (!consensusBlockId_.isEmpty()) {
        output.writeBytes(4, consensusBlockId_);
      }
      if (epochNum_ != 0L) {
        output.writeUInt64(5, epochNum_);
      }
      if (timestampUsecs_ != 0L) {
        output.writeUInt64(6, timestampUsecs_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (version_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, version_);
      }
      if (!transactionAccumulatorHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, transactionAccumulatorHash_);
      }
      if (!consensusDataHash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, consensusDataHash_);
      }
      if (!consensusBlockId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, consensusBlockId_);
      }
      if (epochNum_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, epochNum_);
      }
      if (timestampUsecs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, timestampUsecs_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof types.LedgerInfoOuterClass.LedgerInfo)) {
        return super.equals(obj);
      }
      types.LedgerInfoOuterClass.LedgerInfo other = (types.LedgerInfoOuterClass.LedgerInfo) obj;

      boolean result = true;
      result = result && (getVersion()
          == other.getVersion());
      result = result && getTransactionAccumulatorHash()
          .equals(other.getTransactionAccumulatorHash());
      result = result && getConsensusDataHash()
          .equals(other.getConsensusDataHash());
      result = result && getConsensusBlockId()
          .equals(other.getConsensusBlockId());
      result = result && (getEpochNum()
          == other.getEpochNum());
      result = result && (getTimestampUsecs()
          == other.getTimestampUsecs());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getVersion());
      hash = (37 * hash) + TRANSACTION_ACCUMULATOR_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getTransactionAccumulatorHash().hashCode();
      hash = (37 * hash) + CONSENSUS_DATA_HASH_FIELD_NUMBER;
      hash = (53 * hash) + getConsensusDataHash().hashCode();
      hash = (37 * hash) + CONSENSUS_BLOCK_ID_FIELD_NUMBER;
      hash = (53 * hash) + getConsensusBlockId().hashCode();
      hash = (37 * hash) + EPOCH_NUM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEpochNum());
      hash = (37 * hash) + TIMESTAMP_USECS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestampUsecs());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static types.LedgerInfoOuterClass.LedgerInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static types.LedgerInfoOuterClass.LedgerInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.LedgerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static types.LedgerInfoOuterClass.LedgerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.LedgerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static types.LedgerInfoOuterClass.LedgerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.LedgerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static types.LedgerInfoOuterClass.LedgerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.LedgerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static types.LedgerInfoOuterClass.LedgerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.LedgerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static types.LedgerInfoOuterClass.LedgerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(types.LedgerInfoOuterClass.LedgerInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *&#47; Even though we don't always need all hashes, we pass them in and return them
     * / always so that we keep them in sync on the client and don't make the client
     * / worry about which one(s) to pass in which cases
     * /
     * / This structure serves a dual purpose.
     * /
     * / First, if this structure is signed by 2f+1 validators it signifies the state
     * / of the ledger at version `version` -- it contains the transaction
     * / accumulator at that version which commits to all historical transactions.
     * / This structure may be expanded to include other information that is derived
     * / from that accumulator (e.g. the current time according to the time contract)
     * / to reduce the number of proofs a client must get.
     * /
     * / Second, the structure contains a `consensus_data_hash` value. This is the
     * / hash of an internal data structure that represents a block that is voted on
     * / by consensus.
     * /
     * / Combining these two concepts when the consensus algorithm votes on a block B
     * / it votes for a LedgerInfo with the `version` being the latest version that
     * / will be committed if B gets 2f+1 votes. It sets `consensus_data_hash` to
     * / represent B so that if those 2f+1 votes are gathered, the block is valid to
     * / commit
     * </pre>
     *
     * Protobuf type {@code types.LedgerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:types.LedgerInfo)
        types.LedgerInfoOuterClass.LedgerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return types.LedgerInfoOuterClass.internal_static_types_LedgerInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return types.LedgerInfoOuterClass.internal_static_types_LedgerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                types.LedgerInfoOuterClass.LedgerInfo.class, types.LedgerInfoOuterClass.LedgerInfo.Builder.class);
      }

      // Construct using types.LedgerInfoOuterClass.LedgerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        version_ = 0L;

        transactionAccumulatorHash_ = com.google.protobuf.ByteString.EMPTY;

        consensusDataHash_ = com.google.protobuf.ByteString.EMPTY;

        consensusBlockId_ = com.google.protobuf.ByteString.EMPTY;

        epochNum_ = 0L;

        timestampUsecs_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return types.LedgerInfoOuterClass.internal_static_types_LedgerInfo_descriptor;
      }

      public types.LedgerInfoOuterClass.LedgerInfo getDefaultInstanceForType() {
        return types.LedgerInfoOuterClass.LedgerInfo.getDefaultInstance();
      }

      public types.LedgerInfoOuterClass.LedgerInfo build() {
        types.LedgerInfoOuterClass.LedgerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public types.LedgerInfoOuterClass.LedgerInfo buildPartial() {
        types.LedgerInfoOuterClass.LedgerInfo result = new types.LedgerInfoOuterClass.LedgerInfo(this);
        result.version_ = version_;
        result.transactionAccumulatorHash_ = transactionAccumulatorHash_;
        result.consensusDataHash_ = consensusDataHash_;
        result.consensusBlockId_ = consensusBlockId_;
        result.epochNum_ = epochNum_;
        result.timestampUsecs_ = timestampUsecs_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof types.LedgerInfoOuterClass.LedgerInfo) {
          return mergeFrom((types.LedgerInfoOuterClass.LedgerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(types.LedgerInfoOuterClass.LedgerInfo other) {
        if (other == types.LedgerInfoOuterClass.LedgerInfo.getDefaultInstance()) return this;
        if (other.getVersion() != 0L) {
          setVersion(other.getVersion());
        }
        if (other.getTransactionAccumulatorHash() != com.google.protobuf.ByteString.EMPTY) {
          setTransactionAccumulatorHash(other.getTransactionAccumulatorHash());
        }
        if (other.getConsensusDataHash() != com.google.protobuf.ByteString.EMPTY) {
          setConsensusDataHash(other.getConsensusDataHash());
        }
        if (other.getConsensusBlockId() != com.google.protobuf.ByteString.EMPTY) {
          setConsensusBlockId(other.getConsensusBlockId());
        }
        if (other.getEpochNum() != 0L) {
          setEpochNum(other.getEpochNum());
        }
        if (other.getTimestampUsecs() != 0L) {
          setTimestampUsecs(other.getTimestampUsecs());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        types.LedgerInfoOuterClass.LedgerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (types.LedgerInfoOuterClass.LedgerInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long version_ ;
      /**
       * <pre>
       * Current latest version of the system
       * </pre>
       *
       * <code>uint64 version = 1;</code>
       */
      public long getVersion() {
        return version_;
      }
      /**
       * <pre>
       * Current latest version of the system
       * </pre>
       *
       * <code>uint64 version = 1;</code>
       */
      public Builder setVersion(long value) {
        
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Current latest version of the system
       * </pre>
       *
       * <code>uint64 version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString transactionAccumulatorHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Root hash of transaction accumulator at this version
       * </pre>
       *
       * <code>bytes transaction_accumulator_hash = 2;</code>
       */
      public com.google.protobuf.ByteString getTransactionAccumulatorHash() {
        return transactionAccumulatorHash_;
      }
      /**
       * <pre>
       * Root hash of transaction accumulator at this version
       * </pre>
       *
       * <code>bytes transaction_accumulator_hash = 2;</code>
       */
      public Builder setTransactionAccumulatorHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        transactionAccumulatorHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Root hash of transaction accumulator at this version
       * </pre>
       *
       * <code>bytes transaction_accumulator_hash = 2;</code>
       */
      public Builder clearTransactionAccumulatorHash() {
        
        transactionAccumulatorHash_ = getDefaultInstance().getTransactionAccumulatorHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString consensusDataHash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Hash of consensus-specific data that is opaque to all parts of the system
       * other than consensus.  This is needed to verify signatures because
       * consensus signing includes this hash
       * </pre>
       *
       * <code>bytes consensus_data_hash = 3;</code>
       */
      public com.google.protobuf.ByteString getConsensusDataHash() {
        return consensusDataHash_;
      }
      /**
       * <pre>
       * Hash of consensus-specific data that is opaque to all parts of the system
       * other than consensus.  This is needed to verify signatures because
       * consensus signing includes this hash
       * </pre>
       *
       * <code>bytes consensus_data_hash = 3;</code>
       */
      public Builder setConsensusDataHash(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        consensusDataHash_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Hash of consensus-specific data that is opaque to all parts of the system
       * other than consensus.  This is needed to verify signatures because
       * consensus signing includes this hash
       * </pre>
       *
       * <code>bytes consensus_data_hash = 3;</code>
       */
      public Builder clearConsensusDataHash() {
        
        consensusDataHash_ = getDefaultInstance().getConsensusDataHash();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString consensusBlockId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The block id of the last committed block corresponding to this ledger info.
       * This field is not particularly interesting to the clients, but can be used
       * by the validators for synchronization.
       * </pre>
       *
       * <code>bytes consensus_block_id = 4;</code>
       */
      public com.google.protobuf.ByteString getConsensusBlockId() {
        return consensusBlockId_;
      }
      /**
       * <pre>
       * The block id of the last committed block corresponding to this ledger info.
       * This field is not particularly interesting to the clients, but can be used
       * by the validators for synchronization.
       * </pre>
       *
       * <code>bytes consensus_block_id = 4;</code>
       */
      public Builder setConsensusBlockId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        consensusBlockId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The block id of the last committed block corresponding to this ledger info.
       * This field is not particularly interesting to the clients, but can be used
       * by the validators for synchronization.
       * </pre>
       *
       * <code>bytes consensus_block_id = 4;</code>
       */
      public Builder clearConsensusBlockId() {
        
        consensusBlockId_ = getDefaultInstance().getConsensusBlockId();
        onChanged();
        return this;
      }

      private long epochNum_ ;
      /**
       * <pre>
       * Epoch number corresponds to the set of validators that are active for this
       * ledger info. The main motivation for keeping the epoch number in the
       * LedgerInfo is to ensure that the client has enough information to verify
       * that the signatures for this info are coming from the validators that
       * indeed form a quorum. Without epoch number a potential attack could reuse
       * the signatures from the validators in one epoch in order to sign the wrong
       * info belonging to another epoch, in which these validators do not form a
       * quorum. The very first epoch number is 0.
       * </pre>
       *
       * <code>uint64 epoch_num = 5;</code>
       */
      public long getEpochNum() {
        return epochNum_;
      }
      /**
       * <pre>
       * Epoch number corresponds to the set of validators that are active for this
       * ledger info. The main motivation for keeping the epoch number in the
       * LedgerInfo is to ensure that the client has enough information to verify
       * that the signatures for this info are coming from the validators that
       * indeed form a quorum. Without epoch number a potential attack could reuse
       * the signatures from the validators in one epoch in order to sign the wrong
       * info belonging to another epoch, in which these validators do not form a
       * quorum. The very first epoch number is 0.
       * </pre>
       *
       * <code>uint64 epoch_num = 5;</code>
       */
      public Builder setEpochNum(long value) {
        
        epochNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Epoch number corresponds to the set of validators that are active for this
       * ledger info. The main motivation for keeping the epoch number in the
       * LedgerInfo is to ensure that the client has enough information to verify
       * that the signatures for this info are coming from the validators that
       * indeed form a quorum. Without epoch number a potential attack could reuse
       * the signatures from the validators in one epoch in order to sign the wrong
       * info belonging to another epoch, in which these validators do not form a
       * quorum. The very first epoch number is 0.
       * </pre>
       *
       * <code>uint64 epoch_num = 5;</code>
       */
      public Builder clearEpochNum() {
        
        epochNum_ = 0L;
        onChanged();
        return this;
      }

      private long timestampUsecs_ ;
      /**
       * <pre>
       * Timestamp that represents the microseconds since the epoch (unix time) that is
       * generated by the proposer of the block.  This is strictly increasing with every block.
       * If a client reads a timestamp &gt; the one they specified for transaction expiration time,
       * they can be certain that their transaction will never be included in a block in the future
       * (assuming that their transaction has not yet been included)
       * </pre>
       *
       * <code>uint64 timestamp_usecs = 6;</code>
       */
      public long getTimestampUsecs() {
        return timestampUsecs_;
      }
      /**
       * <pre>
       * Timestamp that represents the microseconds since the epoch (unix time) that is
       * generated by the proposer of the block.  This is strictly increasing with every block.
       * If a client reads a timestamp &gt; the one they specified for transaction expiration time,
       * they can be certain that their transaction will never be included in a block in the future
       * (assuming that their transaction has not yet been included)
       * </pre>
       *
       * <code>uint64 timestamp_usecs = 6;</code>
       */
      public Builder setTimestampUsecs(long value) {
        
        timestampUsecs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Timestamp that represents the microseconds since the epoch (unix time) that is
       * generated by the proposer of the block.  This is strictly increasing with every block.
       * If a client reads a timestamp &gt; the one they specified for transaction expiration time,
       * they can be certain that their transaction will never be included in a block in the future
       * (assuming that their transaction has not yet been included)
       * </pre>
       *
       * <code>uint64 timestamp_usecs = 6;</code>
       */
      public Builder clearTimestampUsecs() {
        
        timestampUsecs_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:types.LedgerInfo)
    }

    // @@protoc_insertion_point(class_scope:types.LedgerInfo)
    private static final types.LedgerInfoOuterClass.LedgerInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new types.LedgerInfoOuterClass.LedgerInfo();
    }

    public static types.LedgerInfoOuterClass.LedgerInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LedgerInfo>
        PARSER = new com.google.protobuf.AbstractParser<LedgerInfo>() {
      public LedgerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LedgerInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LedgerInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LedgerInfo> getParserForType() {
      return PARSER;
    }

    public types.LedgerInfoOuterClass.LedgerInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LedgerInfoWithSignaturesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:types.LedgerInfoWithSignatures)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Signatures of the root node from each validator
     * </pre>
     *
     * <code>repeated .types.ValidatorSignature signatures = 1;</code>
     */
    java.util.List<types.LedgerInfoOuterClass.ValidatorSignature> 
        getSignaturesList();
    /**
     * <pre>
     * Signatures of the root node from each validator
     * </pre>
     *
     * <code>repeated .types.ValidatorSignature signatures = 1;</code>
     */
    types.LedgerInfoOuterClass.ValidatorSignature getSignatures(int index);
    /**
     * <pre>
     * Signatures of the root node from each validator
     * </pre>
     *
     * <code>repeated .types.ValidatorSignature signatures = 1;</code>
     */
    int getSignaturesCount();
    /**
     * <pre>
     * Signatures of the root node from each validator
     * </pre>
     *
     * <code>repeated .types.ValidatorSignature signatures = 1;</code>
     */
    java.util.List<? extends types.LedgerInfoOuterClass.ValidatorSignatureOrBuilder> 
        getSignaturesOrBuilderList();
    /**
     * <pre>
     * Signatures of the root node from each validator
     * </pre>
     *
     * <code>repeated .types.ValidatorSignature signatures = 1;</code>
     */
    types.LedgerInfoOuterClass.ValidatorSignatureOrBuilder getSignaturesOrBuilder(
        int index);

    /**
     * <code>.types.LedgerInfo ledger_info = 2;</code>
     */
    boolean hasLedgerInfo();
    /**
     * <code>.types.LedgerInfo ledger_info = 2;</code>
     */
    types.LedgerInfoOuterClass.LedgerInfo getLedgerInfo();
    /**
     * <code>.types.LedgerInfo ledger_info = 2;</code>
     */
    types.LedgerInfoOuterClass.LedgerInfoOrBuilder getLedgerInfoOrBuilder();
  }
  /**
   * <pre>
   *&#47; The validator node returns this structure which includes signatures
   * / from each validator to confirm the state.  The client needs to only pass
   * / back the LedgerInfo element since the validator node doesn't need to know
   * / the signatures again when the client performs a query, those are only there
   * / for the client to be able to verify the state
   * </pre>
   *
   * Protobuf type {@code types.LedgerInfoWithSignatures}
   */
  public  static final class LedgerInfoWithSignatures extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:types.LedgerInfoWithSignatures)
      LedgerInfoWithSignaturesOrBuilder {
    // Use LedgerInfoWithSignatures.newBuilder() to construct.
    private LedgerInfoWithSignatures(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LedgerInfoWithSignatures() {
      signatures_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LedgerInfoWithSignatures(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                signatures_ = new java.util.ArrayList<types.LedgerInfoOuterClass.ValidatorSignature>();
                mutable_bitField0_ |= 0x00000001;
              }
              signatures_.add(
                  input.readMessage(types.LedgerInfoOuterClass.ValidatorSignature.parser(), extensionRegistry));
              break;
            }
            case 18: {
              types.LedgerInfoOuterClass.LedgerInfo.Builder subBuilder = null;
              if (ledgerInfo_ != null) {
                subBuilder = ledgerInfo_.toBuilder();
              }
              ledgerInfo_ = input.readMessage(types.LedgerInfoOuterClass.LedgerInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ledgerInfo_);
                ledgerInfo_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          signatures_ = java.util.Collections.unmodifiableList(signatures_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return types.LedgerInfoOuterClass.internal_static_types_LedgerInfoWithSignatures_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return types.LedgerInfoOuterClass.internal_static_types_LedgerInfoWithSignatures_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              types.LedgerInfoOuterClass.LedgerInfoWithSignatures.class, types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder.class);
    }

    private int bitField0_;
    public static final int SIGNATURES_FIELD_NUMBER = 1;
    private java.util.List<types.LedgerInfoOuterClass.ValidatorSignature> signatures_;
    /**
     * <pre>
     * Signatures of the root node from each validator
     * </pre>
     *
     * <code>repeated .types.ValidatorSignature signatures = 1;</code>
     */
    public java.util.List<types.LedgerInfoOuterClass.ValidatorSignature> getSignaturesList() {
      return signatures_;
    }
    /**
     * <pre>
     * Signatures of the root node from each validator
     * </pre>
     *
     * <code>repeated .types.ValidatorSignature signatures = 1;</code>
     */
    public java.util.List<? extends types.LedgerInfoOuterClass.ValidatorSignatureOrBuilder> 
        getSignaturesOrBuilderList() {
      return signatures_;
    }
    /**
     * <pre>
     * Signatures of the root node from each validator
     * </pre>
     *
     * <code>repeated .types.ValidatorSignature signatures = 1;</code>
     */
    public int getSignaturesCount() {
      return signatures_.size();
    }
    /**
     * <pre>
     * Signatures of the root node from each validator
     * </pre>
     *
     * <code>repeated .types.ValidatorSignature signatures = 1;</code>
     */
    public types.LedgerInfoOuterClass.ValidatorSignature getSignatures(int index) {
      return signatures_.get(index);
    }
    /**
     * <pre>
     * Signatures of the root node from each validator
     * </pre>
     *
     * <code>repeated .types.ValidatorSignature signatures = 1;</code>
     */
    public types.LedgerInfoOuterClass.ValidatorSignatureOrBuilder getSignaturesOrBuilder(
        int index) {
      return signatures_.get(index);
    }

    public static final int LEDGER_INFO_FIELD_NUMBER = 2;
    private types.LedgerInfoOuterClass.LedgerInfo ledgerInfo_;
    /**
     * <code>.types.LedgerInfo ledger_info = 2;</code>
     */
    public boolean hasLedgerInfo() {
      return ledgerInfo_ != null;
    }
    /**
     * <code>.types.LedgerInfo ledger_info = 2;</code>
     */
    public types.LedgerInfoOuterClass.LedgerInfo getLedgerInfo() {
      return ledgerInfo_ == null ? types.LedgerInfoOuterClass.LedgerInfo.getDefaultInstance() : ledgerInfo_;
    }
    /**
     * <code>.types.LedgerInfo ledger_info = 2;</code>
     */
    public types.LedgerInfoOuterClass.LedgerInfoOrBuilder getLedgerInfoOrBuilder() {
      return getLedgerInfo();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < signatures_.size(); i++) {
        output.writeMessage(1, signatures_.get(i));
      }
      if (ledgerInfo_ != null) {
        output.writeMessage(2, getLedgerInfo());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < signatures_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, signatures_.get(i));
      }
      if (ledgerInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLedgerInfo());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof types.LedgerInfoOuterClass.LedgerInfoWithSignatures)) {
        return super.equals(obj);
      }
      types.LedgerInfoOuterClass.LedgerInfoWithSignatures other = (types.LedgerInfoOuterClass.LedgerInfoWithSignatures) obj;

      boolean result = true;
      result = result && getSignaturesList()
          .equals(other.getSignaturesList());
      result = result && (hasLedgerInfo() == other.hasLedgerInfo());
      if (hasLedgerInfo()) {
        result = result && getLedgerInfo()
            .equals(other.getLedgerInfo());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSignaturesCount() > 0) {
        hash = (37 * hash) + SIGNATURES_FIELD_NUMBER;
        hash = (53 * hash) + getSignaturesList().hashCode();
      }
      if (hasLedgerInfo()) {
        hash = (37 * hash) + LEDGER_INFO_FIELD_NUMBER;
        hash = (53 * hash) + getLedgerInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(types.LedgerInfoOuterClass.LedgerInfoWithSignatures prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *&#47; The validator node returns this structure which includes signatures
     * / from each validator to confirm the state.  The client needs to only pass
     * / back the LedgerInfo element since the validator node doesn't need to know
     * / the signatures again when the client performs a query, those are only there
     * / for the client to be able to verify the state
     * </pre>
     *
     * Protobuf type {@code types.LedgerInfoWithSignatures}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:types.LedgerInfoWithSignatures)
        types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return types.LedgerInfoOuterClass.internal_static_types_LedgerInfoWithSignatures_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return types.LedgerInfoOuterClass.internal_static_types_LedgerInfoWithSignatures_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                types.LedgerInfoOuterClass.LedgerInfoWithSignatures.class, types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder.class);
      }

      // Construct using types.LedgerInfoOuterClass.LedgerInfoWithSignatures.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSignaturesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (signaturesBuilder_ == null) {
          signatures_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          signaturesBuilder_.clear();
        }
        if (ledgerInfoBuilder_ == null) {
          ledgerInfo_ = null;
        } else {
          ledgerInfo_ = null;
          ledgerInfoBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return types.LedgerInfoOuterClass.internal_static_types_LedgerInfoWithSignatures_descriptor;
      }

      public types.LedgerInfoOuterClass.LedgerInfoWithSignatures getDefaultInstanceForType() {
        return types.LedgerInfoOuterClass.LedgerInfoWithSignatures.getDefaultInstance();
      }

      public types.LedgerInfoOuterClass.LedgerInfoWithSignatures build() {
        types.LedgerInfoOuterClass.LedgerInfoWithSignatures result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public types.LedgerInfoOuterClass.LedgerInfoWithSignatures buildPartial() {
        types.LedgerInfoOuterClass.LedgerInfoWithSignatures result = new types.LedgerInfoOuterClass.LedgerInfoWithSignatures(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (signaturesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            signatures_ = java.util.Collections.unmodifiableList(signatures_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.signatures_ = signatures_;
        } else {
          result.signatures_ = signaturesBuilder_.build();
        }
        if (ledgerInfoBuilder_ == null) {
          result.ledgerInfo_ = ledgerInfo_;
        } else {
          result.ledgerInfo_ = ledgerInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof types.LedgerInfoOuterClass.LedgerInfoWithSignatures) {
          return mergeFrom((types.LedgerInfoOuterClass.LedgerInfoWithSignatures)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(types.LedgerInfoOuterClass.LedgerInfoWithSignatures other) {
        if (other == types.LedgerInfoOuterClass.LedgerInfoWithSignatures.getDefaultInstance()) return this;
        if (signaturesBuilder_ == null) {
          if (!other.signatures_.isEmpty()) {
            if (signatures_.isEmpty()) {
              signatures_ = other.signatures_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSignaturesIsMutable();
              signatures_.addAll(other.signatures_);
            }
            onChanged();
          }
        } else {
          if (!other.signatures_.isEmpty()) {
            if (signaturesBuilder_.isEmpty()) {
              signaturesBuilder_.dispose();
              signaturesBuilder_ = null;
              signatures_ = other.signatures_;
              bitField0_ = (bitField0_ & ~0x00000001);
              signaturesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSignaturesFieldBuilder() : null;
            } else {
              signaturesBuilder_.addAllMessages(other.signatures_);
            }
          }
        }
        if (other.hasLedgerInfo()) {
          mergeLedgerInfo(other.getLedgerInfo());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        types.LedgerInfoOuterClass.LedgerInfoWithSignatures parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (types.LedgerInfoOuterClass.LedgerInfoWithSignatures) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<types.LedgerInfoOuterClass.ValidatorSignature> signatures_ =
        java.util.Collections.emptyList();
      private void ensureSignaturesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          signatures_ = new java.util.ArrayList<types.LedgerInfoOuterClass.ValidatorSignature>(signatures_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          types.LedgerInfoOuterClass.ValidatorSignature, types.LedgerInfoOuterClass.ValidatorSignature.Builder, types.LedgerInfoOuterClass.ValidatorSignatureOrBuilder> signaturesBuilder_;

      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public java.util.List<types.LedgerInfoOuterClass.ValidatorSignature> getSignaturesList() {
        if (signaturesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(signatures_);
        } else {
          return signaturesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public int getSignaturesCount() {
        if (signaturesBuilder_ == null) {
          return signatures_.size();
        } else {
          return signaturesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public types.LedgerInfoOuterClass.ValidatorSignature getSignatures(int index) {
        if (signaturesBuilder_ == null) {
          return signatures_.get(index);
        } else {
          return signaturesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public Builder setSignatures(
          int index, types.LedgerInfoOuterClass.ValidatorSignature value) {
        if (signaturesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSignaturesIsMutable();
          signatures_.set(index, value);
          onChanged();
        } else {
          signaturesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public Builder setSignatures(
          int index, types.LedgerInfoOuterClass.ValidatorSignature.Builder builderForValue) {
        if (signaturesBuilder_ == null) {
          ensureSignaturesIsMutable();
          signatures_.set(index, builderForValue.build());
          onChanged();
        } else {
          signaturesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public Builder addSignatures(types.LedgerInfoOuterClass.ValidatorSignature value) {
        if (signaturesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSignaturesIsMutable();
          signatures_.add(value);
          onChanged();
        } else {
          signaturesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public Builder addSignatures(
          int index, types.LedgerInfoOuterClass.ValidatorSignature value) {
        if (signaturesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSignaturesIsMutable();
          signatures_.add(index, value);
          onChanged();
        } else {
          signaturesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public Builder addSignatures(
          types.LedgerInfoOuterClass.ValidatorSignature.Builder builderForValue) {
        if (signaturesBuilder_ == null) {
          ensureSignaturesIsMutable();
          signatures_.add(builderForValue.build());
          onChanged();
        } else {
          signaturesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public Builder addSignatures(
          int index, types.LedgerInfoOuterClass.ValidatorSignature.Builder builderForValue) {
        if (signaturesBuilder_ == null) {
          ensureSignaturesIsMutable();
          signatures_.add(index, builderForValue.build());
          onChanged();
        } else {
          signaturesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public Builder addAllSignatures(
          java.lang.Iterable<? extends types.LedgerInfoOuterClass.ValidatorSignature> values) {
        if (signaturesBuilder_ == null) {
          ensureSignaturesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, signatures_);
          onChanged();
        } else {
          signaturesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public Builder clearSignatures() {
        if (signaturesBuilder_ == null) {
          signatures_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          signaturesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public Builder removeSignatures(int index) {
        if (signaturesBuilder_ == null) {
          ensureSignaturesIsMutable();
          signatures_.remove(index);
          onChanged();
        } else {
          signaturesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public types.LedgerInfoOuterClass.ValidatorSignature.Builder getSignaturesBuilder(
          int index) {
        return getSignaturesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public types.LedgerInfoOuterClass.ValidatorSignatureOrBuilder getSignaturesOrBuilder(
          int index) {
        if (signaturesBuilder_ == null) {
          return signatures_.get(index);  } else {
          return signaturesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public java.util.List<? extends types.LedgerInfoOuterClass.ValidatorSignatureOrBuilder> 
           getSignaturesOrBuilderList() {
        if (signaturesBuilder_ != null) {
          return signaturesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(signatures_);
        }
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public types.LedgerInfoOuterClass.ValidatorSignature.Builder addSignaturesBuilder() {
        return getSignaturesFieldBuilder().addBuilder(
            types.LedgerInfoOuterClass.ValidatorSignature.getDefaultInstance());
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public types.LedgerInfoOuterClass.ValidatorSignature.Builder addSignaturesBuilder(
          int index) {
        return getSignaturesFieldBuilder().addBuilder(
            index, types.LedgerInfoOuterClass.ValidatorSignature.getDefaultInstance());
      }
      /**
       * <pre>
       * Signatures of the root node from each validator
       * </pre>
       *
       * <code>repeated .types.ValidatorSignature signatures = 1;</code>
       */
      public java.util.List<types.LedgerInfoOuterClass.ValidatorSignature.Builder> 
           getSignaturesBuilderList() {
        return getSignaturesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          types.LedgerInfoOuterClass.ValidatorSignature, types.LedgerInfoOuterClass.ValidatorSignature.Builder, types.LedgerInfoOuterClass.ValidatorSignatureOrBuilder> 
          getSignaturesFieldBuilder() {
        if (signaturesBuilder_ == null) {
          signaturesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              types.LedgerInfoOuterClass.ValidatorSignature, types.LedgerInfoOuterClass.ValidatorSignature.Builder, types.LedgerInfoOuterClass.ValidatorSignatureOrBuilder>(
                  signatures_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          signatures_ = null;
        }
        return signaturesBuilder_;
      }

      private types.LedgerInfoOuterClass.LedgerInfo ledgerInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          types.LedgerInfoOuterClass.LedgerInfo, types.LedgerInfoOuterClass.LedgerInfo.Builder, types.LedgerInfoOuterClass.LedgerInfoOrBuilder> ledgerInfoBuilder_;
      /**
       * <code>.types.LedgerInfo ledger_info = 2;</code>
       */
      public boolean hasLedgerInfo() {
        return ledgerInfoBuilder_ != null || ledgerInfo_ != null;
      }
      /**
       * <code>.types.LedgerInfo ledger_info = 2;</code>
       */
      public types.LedgerInfoOuterClass.LedgerInfo getLedgerInfo() {
        if (ledgerInfoBuilder_ == null) {
          return ledgerInfo_ == null ? types.LedgerInfoOuterClass.LedgerInfo.getDefaultInstance() : ledgerInfo_;
        } else {
          return ledgerInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.types.LedgerInfo ledger_info = 2;</code>
       */
      public Builder setLedgerInfo(types.LedgerInfoOuterClass.LedgerInfo value) {
        if (ledgerInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ledgerInfo_ = value;
          onChanged();
        } else {
          ledgerInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.types.LedgerInfo ledger_info = 2;</code>
       */
      public Builder setLedgerInfo(
          types.LedgerInfoOuterClass.LedgerInfo.Builder builderForValue) {
        if (ledgerInfoBuilder_ == null) {
          ledgerInfo_ = builderForValue.build();
          onChanged();
        } else {
          ledgerInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.types.LedgerInfo ledger_info = 2;</code>
       */
      public Builder mergeLedgerInfo(types.LedgerInfoOuterClass.LedgerInfo value) {
        if (ledgerInfoBuilder_ == null) {
          if (ledgerInfo_ != null) {
            ledgerInfo_ =
              types.LedgerInfoOuterClass.LedgerInfo.newBuilder(ledgerInfo_).mergeFrom(value).buildPartial();
          } else {
            ledgerInfo_ = value;
          }
          onChanged();
        } else {
          ledgerInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.types.LedgerInfo ledger_info = 2;</code>
       */
      public Builder clearLedgerInfo() {
        if (ledgerInfoBuilder_ == null) {
          ledgerInfo_ = null;
          onChanged();
        } else {
          ledgerInfo_ = null;
          ledgerInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.types.LedgerInfo ledger_info = 2;</code>
       */
      public types.LedgerInfoOuterClass.LedgerInfo.Builder getLedgerInfoBuilder() {
        
        onChanged();
        return getLedgerInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.types.LedgerInfo ledger_info = 2;</code>
       */
      public types.LedgerInfoOuterClass.LedgerInfoOrBuilder getLedgerInfoOrBuilder() {
        if (ledgerInfoBuilder_ != null) {
          return ledgerInfoBuilder_.getMessageOrBuilder();
        } else {
          return ledgerInfo_ == null ?
              types.LedgerInfoOuterClass.LedgerInfo.getDefaultInstance() : ledgerInfo_;
        }
      }
      /**
       * <code>.types.LedgerInfo ledger_info = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          types.LedgerInfoOuterClass.LedgerInfo, types.LedgerInfoOuterClass.LedgerInfo.Builder, types.LedgerInfoOuterClass.LedgerInfoOrBuilder> 
          getLedgerInfoFieldBuilder() {
        if (ledgerInfoBuilder_ == null) {
          ledgerInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              types.LedgerInfoOuterClass.LedgerInfo, types.LedgerInfoOuterClass.LedgerInfo.Builder, types.LedgerInfoOuterClass.LedgerInfoOrBuilder>(
                  getLedgerInfo(),
                  getParentForChildren(),
                  isClean());
          ledgerInfo_ = null;
        }
        return ledgerInfoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:types.LedgerInfoWithSignatures)
    }

    // @@protoc_insertion_point(class_scope:types.LedgerInfoWithSignatures)
    private static final types.LedgerInfoOuterClass.LedgerInfoWithSignatures DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new types.LedgerInfoOuterClass.LedgerInfoWithSignatures();
    }

    public static types.LedgerInfoOuterClass.LedgerInfoWithSignatures getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LedgerInfoWithSignatures>
        PARSER = new com.google.protobuf.AbstractParser<LedgerInfoWithSignatures>() {
      public LedgerInfoWithSignatures parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LedgerInfoWithSignatures(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LedgerInfoWithSignatures> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LedgerInfoWithSignatures> getParserForType() {
      return PARSER;
    }

    public types.LedgerInfoOuterClass.LedgerInfoWithSignatures getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ValidatorSignatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:types.ValidatorSignature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The account address of the validator, which can be used for retrieving its
     * public key during the given epoch.
     * </pre>
     *
     * <code>bytes validator_id = 1;</code>
     */
    com.google.protobuf.ByteString getValidatorId();

    /**
     * <code>bytes signature = 2;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code types.ValidatorSignature}
   */
  public  static final class ValidatorSignature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:types.ValidatorSignature)
      ValidatorSignatureOrBuilder {
    // Use ValidatorSignature.newBuilder() to construct.
    private ValidatorSignature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValidatorSignature() {
      validatorId_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ValidatorSignature(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              validatorId_ = input.readBytes();
              break;
            }
            case 18: {

              signature_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return types.LedgerInfoOuterClass.internal_static_types_ValidatorSignature_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return types.LedgerInfoOuterClass.internal_static_types_ValidatorSignature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              types.LedgerInfoOuterClass.ValidatorSignature.class, types.LedgerInfoOuterClass.ValidatorSignature.Builder.class);
    }

    public static final int VALIDATOR_ID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString validatorId_;
    /**
     * <pre>
     * The account address of the validator, which can be used for retrieving its
     * public key during the given epoch.
     * </pre>
     *
     * <code>bytes validator_id = 1;</code>
     */
    public com.google.protobuf.ByteString getValidatorId() {
      return validatorId_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 2;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!validatorId_.isEmpty()) {
        output.writeBytes(1, validatorId_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(2, signature_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!validatorId_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, validatorId_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof types.LedgerInfoOuterClass.ValidatorSignature)) {
        return super.equals(obj);
      }
      types.LedgerInfoOuterClass.ValidatorSignature other = (types.LedgerInfoOuterClass.ValidatorSignature) obj;

      boolean result = true;
      result = result && getValidatorId()
          .equals(other.getValidatorId());
      result = result && getSignature()
          .equals(other.getSignature());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALIDATOR_ID_FIELD_NUMBER;
      hash = (53 * hash) + getValidatorId().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static types.LedgerInfoOuterClass.ValidatorSignature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static types.LedgerInfoOuterClass.ValidatorSignature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.ValidatorSignature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static types.LedgerInfoOuterClass.ValidatorSignature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.ValidatorSignature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static types.LedgerInfoOuterClass.ValidatorSignature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.ValidatorSignature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static types.LedgerInfoOuterClass.ValidatorSignature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.ValidatorSignature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static types.LedgerInfoOuterClass.ValidatorSignature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static types.LedgerInfoOuterClass.ValidatorSignature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static types.LedgerInfoOuterClass.ValidatorSignature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(types.LedgerInfoOuterClass.ValidatorSignature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code types.ValidatorSignature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:types.ValidatorSignature)
        types.LedgerInfoOuterClass.ValidatorSignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return types.LedgerInfoOuterClass.internal_static_types_ValidatorSignature_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return types.LedgerInfoOuterClass.internal_static_types_ValidatorSignature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                types.LedgerInfoOuterClass.ValidatorSignature.class, types.LedgerInfoOuterClass.ValidatorSignature.Builder.class);
      }

      // Construct using types.LedgerInfoOuterClass.ValidatorSignature.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        validatorId_ = com.google.protobuf.ByteString.EMPTY;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return types.LedgerInfoOuterClass.internal_static_types_ValidatorSignature_descriptor;
      }

      public types.LedgerInfoOuterClass.ValidatorSignature getDefaultInstanceForType() {
        return types.LedgerInfoOuterClass.ValidatorSignature.getDefaultInstance();
      }

      public types.LedgerInfoOuterClass.ValidatorSignature build() {
        types.LedgerInfoOuterClass.ValidatorSignature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public types.LedgerInfoOuterClass.ValidatorSignature buildPartial() {
        types.LedgerInfoOuterClass.ValidatorSignature result = new types.LedgerInfoOuterClass.ValidatorSignature(this);
        result.validatorId_ = validatorId_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof types.LedgerInfoOuterClass.ValidatorSignature) {
          return mergeFrom((types.LedgerInfoOuterClass.ValidatorSignature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(types.LedgerInfoOuterClass.ValidatorSignature other) {
        if (other == types.LedgerInfoOuterClass.ValidatorSignature.getDefaultInstance()) return this;
        if (other.getValidatorId() != com.google.protobuf.ByteString.EMPTY) {
          setValidatorId(other.getValidatorId());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        types.LedgerInfoOuterClass.ValidatorSignature parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (types.LedgerInfoOuterClass.ValidatorSignature) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString validatorId_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * The account address of the validator, which can be used for retrieving its
       * public key during the given epoch.
       * </pre>
       *
       * <code>bytes validator_id = 1;</code>
       */
      public com.google.protobuf.ByteString getValidatorId() {
        return validatorId_;
      }
      /**
       * <pre>
       * The account address of the validator, which can be used for retrieving its
       * public key during the given epoch.
       * </pre>
       *
       * <code>bytes validator_id = 1;</code>
       */
      public Builder setValidatorId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        validatorId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The account address of the validator, which can be used for retrieving its
       * public key during the given epoch.
       * </pre>
       *
       * <code>bytes validator_id = 1;</code>
       */
      public Builder clearValidatorId() {
        
        validatorId_ = getDefaultInstance().getValidatorId();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 2;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 2;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:types.ValidatorSignature)
    }

    // @@protoc_insertion_point(class_scope:types.ValidatorSignature)
    private static final types.LedgerInfoOuterClass.ValidatorSignature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new types.LedgerInfoOuterClass.ValidatorSignature();
    }

    public static types.LedgerInfoOuterClass.ValidatorSignature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValidatorSignature>
        PARSER = new com.google.protobuf.AbstractParser<ValidatorSignature>() {
      public ValidatorSignature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ValidatorSignature(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValidatorSignature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValidatorSignature> getParserForType() {
      return PARSER;
    }

    public types.LedgerInfoOuterClass.ValidatorSignature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_LedgerInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_LedgerInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_LedgerInfoWithSignatures_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_LedgerInfoWithSignatures_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ValidatorSignature_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ValidatorSignature_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021ledger_info.proto\022\005types\"\250\001\n\nLedgerInf" +
      "o\022\017\n\007version\030\001 \001(\004\022$\n\034transaction_accumu" +
      "lator_hash\030\002 \001(\014\022\033\n\023consensus_data_hash\030" +
      "\003 \001(\014\022\032\n\022consensus_block_id\030\004 \001(\014\022\021\n\tepo" +
      "ch_num\030\005 \001(\004\022\027\n\017timestamp_usecs\030\006 \001(\004\"q\n" +
      "\030LedgerInfoWithSignatures\022-\n\nsignatures\030" +
      "\001 \003(\0132\031.types.ValidatorSignature\022&\n\013ledg" +
      "er_info\030\002 \001(\0132\021.types.LedgerInfo\"=\n\022Vali" +
      "datorSignature\022\024\n\014validator_id\030\001 \001(\014\022\021\n\t" +
      "signature\030\002 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_types_LedgerInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_types_LedgerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_LedgerInfo_descriptor,
        new java.lang.String[] { "Version", "TransactionAccumulatorHash", "ConsensusDataHash", "ConsensusBlockId", "EpochNum", "TimestampUsecs", });
    internal_static_types_LedgerInfoWithSignatures_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_types_LedgerInfoWithSignatures_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_LedgerInfoWithSignatures_descriptor,
        new java.lang.String[] { "Signatures", "LedgerInfo", });
    internal_static_types_ValidatorSignature_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_types_ValidatorSignature_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ValidatorSignature_descriptor,
        new java.lang.String[] { "ValidatorId", "Signature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
