// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: validator_change.proto

package types;

public final class ValidatorChange {
  private ValidatorChange() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ValidatorChangeEventWithProofOrBuilder extends
      // @@protoc_insertion_point(interface_extends:types.ValidatorChangeEventWithProof)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    boolean hasLedgerInfoWithSigs();
    /**
     * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    types.LedgerInfoOuterClass.LedgerInfoWithSignatures getLedgerInfoWithSigs();
    /**
     * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder getLedgerInfoWithSigsOrBuilder();

    /**
     * <code>.types.EventWithProof event_with_proof = 2;</code>
     */
    boolean hasEventWithProof();
    /**
     * <code>.types.EventWithProof event_with_proof = 2;</code>
     */
    types.Events.EventWithProof getEventWithProof();
    /**
     * <code>.types.EventWithProof event_with_proof = 2;</code>
     */
    types.Events.EventWithProofOrBuilder getEventWithProofOrBuilder();
  }
  /**
   * <pre>
   * This is used to prove validator changes.  When a validator is changing, it
   * triggers an event on /validator_change_account/events/sent.  To tell the
   * client about validator changes, we query
   * /validator_change_account/events/sent to get all versions that contain
   * validator changes after the version that we are trying to update from. For
   * each of these versions, the old validator set would have signed the ledger
   * info at that version.  The client needs this as well as the event results +
   * proof.  The client can then verify that these events were under the current
   * tree and that the changes were signed by the old validators (and that the
   * events correctly show which validators are the new validators).
   * This message represents a single validator change event and the proof that
   * corresponds to it
   * </pre>
   *
   * Protobuf type {@code types.ValidatorChangeEventWithProof}
   */
  public  static final class ValidatorChangeEventWithProof extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:types.ValidatorChangeEventWithProof)
      ValidatorChangeEventWithProofOrBuilder {
    // Use ValidatorChangeEventWithProof.newBuilder() to construct.
    private ValidatorChangeEventWithProof(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ValidatorChangeEventWithProof() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ValidatorChangeEventWithProof(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder subBuilder = null;
              if (ledgerInfoWithSigs_ != null) {
                subBuilder = ledgerInfoWithSigs_.toBuilder();
              }
              ledgerInfoWithSigs_ = input.readMessage(types.LedgerInfoOuterClass.LedgerInfoWithSignatures.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ledgerInfoWithSigs_);
                ledgerInfoWithSigs_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              types.Events.EventWithProof.Builder subBuilder = null;
              if (eventWithProof_ != null) {
                subBuilder = eventWithProof_.toBuilder();
              }
              eventWithProof_ = input.readMessage(types.Events.EventWithProof.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(eventWithProof_);
                eventWithProof_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return types.ValidatorChange.internal_static_types_ValidatorChangeEventWithProof_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return types.ValidatorChange.internal_static_types_ValidatorChangeEventWithProof_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              types.ValidatorChange.ValidatorChangeEventWithProof.class, types.ValidatorChange.ValidatorChangeEventWithProof.Builder.class);
    }

    public static final int LEDGER_INFO_WITH_SIGS_FIELD_NUMBER = 1;
    private types.LedgerInfoOuterClass.LedgerInfoWithSignatures ledgerInfoWithSigs_;
    /**
     * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    public boolean hasLedgerInfoWithSigs() {
      return ledgerInfoWithSigs_ != null;
    }
    /**
     * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    public types.LedgerInfoOuterClass.LedgerInfoWithSignatures getLedgerInfoWithSigs() {
      return ledgerInfoWithSigs_ == null ? types.LedgerInfoOuterClass.LedgerInfoWithSignatures.getDefaultInstance() : ledgerInfoWithSigs_;
    }
    /**
     * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
     */
    public types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder getLedgerInfoWithSigsOrBuilder() {
      return getLedgerInfoWithSigs();
    }

    public static final int EVENT_WITH_PROOF_FIELD_NUMBER = 2;
    private types.Events.EventWithProof eventWithProof_;
    /**
     * <code>.types.EventWithProof event_with_proof = 2;</code>
     */
    public boolean hasEventWithProof() {
      return eventWithProof_ != null;
    }
    /**
     * <code>.types.EventWithProof event_with_proof = 2;</code>
     */
    public types.Events.EventWithProof getEventWithProof() {
      return eventWithProof_ == null ? types.Events.EventWithProof.getDefaultInstance() : eventWithProof_;
    }
    /**
     * <code>.types.EventWithProof event_with_proof = 2;</code>
     */
    public types.Events.EventWithProofOrBuilder getEventWithProofOrBuilder() {
      return getEventWithProof();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (ledgerInfoWithSigs_ != null) {
        output.writeMessage(1, getLedgerInfoWithSigs());
      }
      if (eventWithProof_ != null) {
        output.writeMessage(2, getEventWithProof());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (ledgerInfoWithSigs_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLedgerInfoWithSigs());
      }
      if (eventWithProof_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getEventWithProof());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof types.ValidatorChange.ValidatorChangeEventWithProof)) {
        return super.equals(obj);
      }
      types.ValidatorChange.ValidatorChangeEventWithProof other = (types.ValidatorChange.ValidatorChangeEventWithProof) obj;

      boolean result = true;
      result = result && (hasLedgerInfoWithSigs() == other.hasLedgerInfoWithSigs());
      if (hasLedgerInfoWithSigs()) {
        result = result && getLedgerInfoWithSigs()
            .equals(other.getLedgerInfoWithSigs());
      }
      result = result && (hasEventWithProof() == other.hasEventWithProof());
      if (hasEventWithProof()) {
        result = result && getEventWithProof()
            .equals(other.getEventWithProof());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLedgerInfoWithSigs()) {
        hash = (37 * hash) + LEDGER_INFO_WITH_SIGS_FIELD_NUMBER;
        hash = (53 * hash) + getLedgerInfoWithSigs().hashCode();
      }
      if (hasEventWithProof()) {
        hash = (37 * hash) + EVENT_WITH_PROOF_FIELD_NUMBER;
        hash = (53 * hash) + getEventWithProof().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static types.ValidatorChange.ValidatorChangeEventWithProof parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static types.ValidatorChange.ValidatorChangeEventWithProof parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static types.ValidatorChange.ValidatorChangeEventWithProof parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(types.ValidatorChange.ValidatorChangeEventWithProof prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * This is used to prove validator changes.  When a validator is changing, it
     * triggers an event on /validator_change_account/events/sent.  To tell the
     * client about validator changes, we query
     * /validator_change_account/events/sent to get all versions that contain
     * validator changes after the version that we are trying to update from. For
     * each of these versions, the old validator set would have signed the ledger
     * info at that version.  The client needs this as well as the event results +
     * proof.  The client can then verify that these events were under the current
     * tree and that the changes were signed by the old validators (and that the
     * events correctly show which validators are the new validators).
     * This message represents a single validator change event and the proof that
     * corresponds to it
     * </pre>
     *
     * Protobuf type {@code types.ValidatorChangeEventWithProof}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:types.ValidatorChangeEventWithProof)
        types.ValidatorChange.ValidatorChangeEventWithProofOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return types.ValidatorChange.internal_static_types_ValidatorChangeEventWithProof_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return types.ValidatorChange.internal_static_types_ValidatorChangeEventWithProof_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                types.ValidatorChange.ValidatorChangeEventWithProof.class, types.ValidatorChange.ValidatorChangeEventWithProof.Builder.class);
      }

      // Construct using types.ValidatorChange.ValidatorChangeEventWithProof.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (ledgerInfoWithSigsBuilder_ == null) {
          ledgerInfoWithSigs_ = null;
        } else {
          ledgerInfoWithSigs_ = null;
          ledgerInfoWithSigsBuilder_ = null;
        }
        if (eventWithProofBuilder_ == null) {
          eventWithProof_ = null;
        } else {
          eventWithProof_ = null;
          eventWithProofBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return types.ValidatorChange.internal_static_types_ValidatorChangeEventWithProof_descriptor;
      }

      public types.ValidatorChange.ValidatorChangeEventWithProof getDefaultInstanceForType() {
        return types.ValidatorChange.ValidatorChangeEventWithProof.getDefaultInstance();
      }

      public types.ValidatorChange.ValidatorChangeEventWithProof build() {
        types.ValidatorChange.ValidatorChangeEventWithProof result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public types.ValidatorChange.ValidatorChangeEventWithProof buildPartial() {
        types.ValidatorChange.ValidatorChangeEventWithProof result = new types.ValidatorChange.ValidatorChangeEventWithProof(this);
        if (ledgerInfoWithSigsBuilder_ == null) {
          result.ledgerInfoWithSigs_ = ledgerInfoWithSigs_;
        } else {
          result.ledgerInfoWithSigs_ = ledgerInfoWithSigsBuilder_.build();
        }
        if (eventWithProofBuilder_ == null) {
          result.eventWithProof_ = eventWithProof_;
        } else {
          result.eventWithProof_ = eventWithProofBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof types.ValidatorChange.ValidatorChangeEventWithProof) {
          return mergeFrom((types.ValidatorChange.ValidatorChangeEventWithProof)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(types.ValidatorChange.ValidatorChangeEventWithProof other) {
        if (other == types.ValidatorChange.ValidatorChangeEventWithProof.getDefaultInstance()) return this;
        if (other.hasLedgerInfoWithSigs()) {
          mergeLedgerInfoWithSigs(other.getLedgerInfoWithSigs());
        }
        if (other.hasEventWithProof()) {
          mergeEventWithProof(other.getEventWithProof());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        types.ValidatorChange.ValidatorChangeEventWithProof parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (types.ValidatorChange.ValidatorChangeEventWithProof) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private types.LedgerInfoOuterClass.LedgerInfoWithSignatures ledgerInfoWithSigs_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          types.LedgerInfoOuterClass.LedgerInfoWithSignatures, types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder, types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder> ledgerInfoWithSigsBuilder_;
      /**
       * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public boolean hasLedgerInfoWithSigs() {
        return ledgerInfoWithSigsBuilder_ != null || ledgerInfoWithSigs_ != null;
      }
      /**
       * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public types.LedgerInfoOuterClass.LedgerInfoWithSignatures getLedgerInfoWithSigs() {
        if (ledgerInfoWithSigsBuilder_ == null) {
          return ledgerInfoWithSigs_ == null ? types.LedgerInfoOuterClass.LedgerInfoWithSignatures.getDefaultInstance() : ledgerInfoWithSigs_;
        } else {
          return ledgerInfoWithSigsBuilder_.getMessage();
        }
      }
      /**
       * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder setLedgerInfoWithSigs(types.LedgerInfoOuterClass.LedgerInfoWithSignatures value) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ledgerInfoWithSigs_ = value;
          onChanged();
        } else {
          ledgerInfoWithSigsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder setLedgerInfoWithSigs(
          types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder builderForValue) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          ledgerInfoWithSigs_ = builderForValue.build();
          onChanged();
        } else {
          ledgerInfoWithSigsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder mergeLedgerInfoWithSigs(types.LedgerInfoOuterClass.LedgerInfoWithSignatures value) {
        if (ledgerInfoWithSigsBuilder_ == null) {
          if (ledgerInfoWithSigs_ != null) {
            ledgerInfoWithSigs_ =
              types.LedgerInfoOuterClass.LedgerInfoWithSignatures.newBuilder(ledgerInfoWithSigs_).mergeFrom(value).buildPartial();
          } else {
            ledgerInfoWithSigs_ = value;
          }
          onChanged();
        } else {
          ledgerInfoWithSigsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public Builder clearLedgerInfoWithSigs() {
        if (ledgerInfoWithSigsBuilder_ == null) {
          ledgerInfoWithSigs_ = null;
          onChanged();
        } else {
          ledgerInfoWithSigs_ = null;
          ledgerInfoWithSigsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder getLedgerInfoWithSigsBuilder() {
        
        onChanged();
        return getLedgerInfoWithSigsFieldBuilder().getBuilder();
      }
      /**
       * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      public types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder getLedgerInfoWithSigsOrBuilder() {
        if (ledgerInfoWithSigsBuilder_ != null) {
          return ledgerInfoWithSigsBuilder_.getMessageOrBuilder();
        } else {
          return ledgerInfoWithSigs_ == null ?
              types.LedgerInfoOuterClass.LedgerInfoWithSignatures.getDefaultInstance() : ledgerInfoWithSigs_;
        }
      }
      /**
       * <code>.types.LedgerInfoWithSignatures ledger_info_with_sigs = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          types.LedgerInfoOuterClass.LedgerInfoWithSignatures, types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder, types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder> 
          getLedgerInfoWithSigsFieldBuilder() {
        if (ledgerInfoWithSigsBuilder_ == null) {
          ledgerInfoWithSigsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              types.LedgerInfoOuterClass.LedgerInfoWithSignatures, types.LedgerInfoOuterClass.LedgerInfoWithSignatures.Builder, types.LedgerInfoOuterClass.LedgerInfoWithSignaturesOrBuilder>(
                  getLedgerInfoWithSigs(),
                  getParentForChildren(),
                  isClean());
          ledgerInfoWithSigs_ = null;
        }
        return ledgerInfoWithSigsBuilder_;
      }

      private types.Events.EventWithProof eventWithProof_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          types.Events.EventWithProof, types.Events.EventWithProof.Builder, types.Events.EventWithProofOrBuilder> eventWithProofBuilder_;
      /**
       * <code>.types.EventWithProof event_with_proof = 2;</code>
       */
      public boolean hasEventWithProof() {
        return eventWithProofBuilder_ != null || eventWithProof_ != null;
      }
      /**
       * <code>.types.EventWithProof event_with_proof = 2;</code>
       */
      public types.Events.EventWithProof getEventWithProof() {
        if (eventWithProofBuilder_ == null) {
          return eventWithProof_ == null ? types.Events.EventWithProof.getDefaultInstance() : eventWithProof_;
        } else {
          return eventWithProofBuilder_.getMessage();
        }
      }
      /**
       * <code>.types.EventWithProof event_with_proof = 2;</code>
       */
      public Builder setEventWithProof(types.Events.EventWithProof value) {
        if (eventWithProofBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventWithProof_ = value;
          onChanged();
        } else {
          eventWithProofBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.types.EventWithProof event_with_proof = 2;</code>
       */
      public Builder setEventWithProof(
          types.Events.EventWithProof.Builder builderForValue) {
        if (eventWithProofBuilder_ == null) {
          eventWithProof_ = builderForValue.build();
          onChanged();
        } else {
          eventWithProofBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.types.EventWithProof event_with_proof = 2;</code>
       */
      public Builder mergeEventWithProof(types.Events.EventWithProof value) {
        if (eventWithProofBuilder_ == null) {
          if (eventWithProof_ != null) {
            eventWithProof_ =
              types.Events.EventWithProof.newBuilder(eventWithProof_).mergeFrom(value).buildPartial();
          } else {
            eventWithProof_ = value;
          }
          onChanged();
        } else {
          eventWithProofBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.types.EventWithProof event_with_proof = 2;</code>
       */
      public Builder clearEventWithProof() {
        if (eventWithProofBuilder_ == null) {
          eventWithProof_ = null;
          onChanged();
        } else {
          eventWithProof_ = null;
          eventWithProofBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.types.EventWithProof event_with_proof = 2;</code>
       */
      public types.Events.EventWithProof.Builder getEventWithProofBuilder() {
        
        onChanged();
        return getEventWithProofFieldBuilder().getBuilder();
      }
      /**
       * <code>.types.EventWithProof event_with_proof = 2;</code>
       */
      public types.Events.EventWithProofOrBuilder getEventWithProofOrBuilder() {
        if (eventWithProofBuilder_ != null) {
          return eventWithProofBuilder_.getMessageOrBuilder();
        } else {
          return eventWithProof_ == null ?
              types.Events.EventWithProof.getDefaultInstance() : eventWithProof_;
        }
      }
      /**
       * <code>.types.EventWithProof event_with_proof = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          types.Events.EventWithProof, types.Events.EventWithProof.Builder, types.Events.EventWithProofOrBuilder> 
          getEventWithProofFieldBuilder() {
        if (eventWithProofBuilder_ == null) {
          eventWithProofBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              types.Events.EventWithProof, types.Events.EventWithProof.Builder, types.Events.EventWithProofOrBuilder>(
                  getEventWithProof(),
                  getParentForChildren(),
                  isClean());
          eventWithProof_ = null;
        }
        return eventWithProofBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:types.ValidatorChangeEventWithProof)
    }

    // @@protoc_insertion_point(class_scope:types.ValidatorChangeEventWithProof)
    private static final types.ValidatorChange.ValidatorChangeEventWithProof DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new types.ValidatorChange.ValidatorChangeEventWithProof();
    }

    public static types.ValidatorChange.ValidatorChangeEventWithProof getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ValidatorChangeEventWithProof>
        PARSER = new com.google.protobuf.AbstractParser<ValidatorChangeEventWithProof>() {
      public ValidatorChangeEventWithProof parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ValidatorChangeEventWithProof(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ValidatorChangeEventWithProof> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ValidatorChangeEventWithProof> getParserForType() {
      return PARSER;
    }

    public types.ValidatorChange.ValidatorChangeEventWithProof getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_types_ValidatorChangeEventWithProof_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_types_ValidatorChangeEventWithProof_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026validator_change.proto\022\005types\032\014events." +
      "proto\032\021ledger_info.proto\"\220\001\n\035ValidatorCh" +
      "angeEventWithProof\022>\n\025ledger_info_with_s" +
      "igs\030\001 \001(\0132\037.types.LedgerInfoWithSignatur" +
      "es\022/\n\020event_with_proof\030\002 \001(\0132\025.types.Eve" +
      "ntWithProofb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          types.Events.getDescriptor(),
          types.LedgerInfoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_types_ValidatorChangeEventWithProof_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_types_ValidatorChangeEventWithProof_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_types_ValidatorChangeEventWithProof_descriptor,
        new java.lang.String[] { "LedgerInfoWithSigs", "EventWithProof", });
    types.Events.getDescriptor();
    types.LedgerInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
